# .goreleaser.yml
version: 2

builds:
  - main: ./main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macOS

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts:
      - binaries
    cmd: gpg --detach-sign --armor
    args:
      - "{{ .ArtifactName }}"

release:
  github:
    owner: Itzhep
    name: gomon
    token: $GITHUB_TOKEN
    draft: false
    prerelease: false
