version: '3.8'

services:
  gomon:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: go run main.go
    ports:
      - "35729:35729" # Live reload server port

version: '3.8'

services:
  gomon:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: go run main.go 

